name: Build and Deploy to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false

      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
        
      - name: Build
        run: ./gradlew build
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/distributions
          CLEAN: true
